require 'faker'
p 'Seeding DB'

Product.destroy_all
Category.destroy_all

cat = [
  {
    name: 'soups'
  },
  {
    name: 'mexican'
  },
  {
    name: 'sushi'
  },
  {
    name: 'italian'
  },
  {
    name: 'snack'
  }
]

products = [
  { name: 'green cream',
    url_image: 'https://img.freepik.com/free-photo/top-view-green-cream-soups_23-2148519096.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 1 },
  { name: 'organic pumpkin',
    url_image: 'https://img.freepik.com/free-photo/organic-pumpkin-puree-white-bowl_193819-1820.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 1 },
  { name: 'broccoli soup',
    url_image: 'https://img.freepik.com/free-photo/flat-lay-homemade-soup-broccoli-spinach_23-2148452773.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 1 },
  { name: 'zucchini cream',
    url_image: 'https://img.freepik.com/free-photo/zucchini-cream-soup-with-garlic-chilli_2829-19613.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 1 },
  { name: 'asian ramen',
    url_image: 'https://img.freepik.com/free-photo/traditional-asian-ramen-soup-with-onion-egg-pork-corn-parsley-hot-pepper-black-bowl-black-surface-with-reflection_207126-3157.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 1 },
  { name: 'tortilla mix',
    url_image: 'https://img.freepik.com/free-photo/tortilla-with-mix-ingredients_62847-293.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'spicy nachos',
    url_image: 'https://img.freepik.com/free-photo/mexican-spicy-food-nachos-top-view_23-2148224125.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'barquita taco',
    url_image: 'https://img.freepik.com/free-photo/mexican-barquita-taco-with-beef-chilli-tomato-onion-spices-wooden-table_123827-15005.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'quesadillas wrap',
    url_image: 'https://img.freepik.com/free-photo/mexican-quesadilla-wrap-with-chicken-corn-sweet-pepper-salsa_2829-19734.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'nachos chips',
    url_image: 'https://img.freepik.com/free-photo/plate-nacho-chips-with-homemade-salsa_23-2148181587.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'veggie tacos',
    url_image: 'https://img.freepik.com/free-photo/mexican-appetizer-tacos-with-vegetables_127425-270.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 2 },
  { name: 'shrimp tempura',
    url_image: 'https://image.freepik.com/free-photo/side-view-shrimp-tempura-roll-sushi_141793-3273.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 3 },
  { name: 'mix rolls',
    url_image: 'https://image.freepik.com/free-photo/traditional-japanese-sushi-rolls-cutting-boards_220768-8.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 3 },
  { name: 'combo makis',
    url_image: 'https://image.freepik.com/free-photo/top-view-sushi-set-with-soy-sauce-chopsticks-wooden-serving-board_176474-3466.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 3 },
  { name: 'rissoto',
    url_image: 'https://img.freepik.com/free-photo/italian-risotto-with-shrimps_1339-82453.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 4 },
  { name: 'chicken spagetti',
    url_image: 'https://img.freepik.com/free-photo/chicken-spaghetti-pasta-white-wooden-background-with-italian-food_1205-3969.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 4 },
  { name: 'penne carbonara',
    url_image: 'https://img.freepik.com/free-photo/penne-carbonara-pasta-with-salmon_74190-2784.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 4 },
  { name: 'stir fried spaghetti',
    url_image: 'https://img.freepik.com/free-photo/stir-fried-spaghetti-with-chicken-basil_1339-106679.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 4 },
  { name: 'spaghetti with tomato',
    url_image: 'https://img.freepik.com/free-photo/pasta-spaghetti-with-tomato-sauce-black-bowl-top-view_170884-14.jpg',
    price: rand(1000..5000),
    discount: rand(10..40),
    category_id: 4 },
  { name: 'popcorn',
    url_image: 'https://img.freepik.com/free-photo/top-view-bucket-popcorns_114309-228.jpg',
    price: rand(500..2000),
    discount: rand(5..40),
    category_id: 5 },
  { name: 'cookies mix',
    url_image: 'https://img.freepik.com/free-photo/assortment-salt-crackers-shot-from-top-colorful-with-copy-salty-party-snacks-mix_114579-3815.jpg',
    price: rand(500..2000),
    discount: rand(5..40),
    category_id: 5 },
  { name: 'potato chips',
    url_image: 'https://img.freepik.com/free-photo/close-up-potato-chips-wood-top-view-background_120872-5307.jpg',
    price: rand(500..2000),
    discount: rand(5..40),
    category_id: 5 },
  { name: 'pretzels',
    url_image: 'https://img.freepik.com/free-photo/top-view-pretzels-arrangement_23-2148582666.jpg',
    price: rand(500..2000),
    discount: rand(5..40),
    category_id: 5 },
  { name: 'nuts',
    url_image: 'https://img.freepik.com/free-photo/mixture-roasted-nuts-with-salt-pepper-masala-pulses-channa-masala-dal-green-peas-blue-bowl_136354-6214.jpg',
    price: rand(500..2000),
    discount: rand(5..40),
    category_id: 5 }
]
cat.each { |catego| Category.create(catego) }
p 'category finished'
products.each { |product| Product.create(product) }

p 'Seeding finished'
